name: Restrict PR Source

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**/*.ts"
      - "**/package.json"
      - '.github/workflows/jest.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "Only dev branch can open PR to main"
            exit 1
          fi
